name: uHomes
version: '${project.version}'
main: me.usainsrht.uhomes.UHomes
api-version: '1.21'
authors:
  - UsainSrht
dependencies:
  server:
    Lands:
      load: BEFORE
      required: false
      join-classpath: true
    GriefPrevention:
      load: BEFORE
      required: false
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true